// Generated by CoffeeScript 1.12.4
var crawlModule, emptyFunction, initModule, transformFiles;

emptyFunction = require("emptyFunction");

transformFiles = require("./transformFiles");

initModule = require("./initModule");

module.exports = function(options) {
  var allFiles, moduleNames;
  moduleNames = options._;
  if (!moduleNames.length) {
    return crawlModule(".").then(function(files) {
      return transformFiles(files, options);
    });
  }
  allFiles = [];
  return Promise.chain(moduleNames, function(moduleName) {
    return crawlModule(moduleName).then(function(files) {
      return allFiles = allFiles.concat(files);
    });
  }).then(function() {
    return transformFiles(allFiles, options);
  });
};

crawlModule = function(moduleName) {
  return lotus.Module.load(moduleName).then(function(module) {
    return initModule(module).then(function(patterns) {
      return module.crawl(patterns, {
        ignore: "**/{node_modules,__tests__,__mocks__}/**"
      });
    }).fail(function(error) {
      log.moat(1);
      log.red("Module error: ");
      log.white(module.path);
      log.moat(0);
      log.gray.dim(error.stack);
      return log.moat(1);
    });
  });
};
