// Generated by CoffeeScript 1.12.4
exports.initCommands = function() {
  return {
    babel: function() {
      return require("./cli");
    }
  };
};

exports.initModule = function() {
  return require("./watchModule");
};

exports.globalDependencies = ["lotus-watch"];
