// Generated by CoffeeScript 1.12.4
module.exports = {
  loadCommands: function() {
    return require("./cli");
  },
  initModule: function() {
    return require("./watchModule");
  },
  globalDependencies: ["lotus-watch"]
};
