// Generated by CoffeeScript 1.12.4
var fs, rimraf;

rimraf = require("rimraf");

fs = require("fsx");

module.exports = function(module, options) {
  if (options == null) {
    options = {};
  }
  return module.load(["config"]).then(function() {
    var patterns;
    if (module.src == null) {
      module.src = "src";
    }
    if (module.spec == null) {
      module.spec = "spec";
    }
    if (module.dest) {
      if (options.refresh) {
        rimraf.sync(module.dest);
      }
      fs.writeDir(module.dest);
    }
    if (module.specDest) {
      if (options.refresh) {
        rimraf.sync(module.specDest);
      }
      fs.writeDir(module.specDest);
    }
    patterns = [];
    if (fs.isDir(module.src)) {
      patterns.push(module.src + "/**/*.js");
    }
    if (fs.isDir(module.spec)) {
      patterns.push(module.spec + "/**/*.js");
    }
    return patterns;
  });
};
