// Generated by CoffeeScript 1.12.4
var fs, path, rimraf;

rimraf = require("rimraf");

path = require("path");

fs = require("fsx");

module.exports = function(mod, options) {
  if (options == null) {
    options = {};
  }
  return mod.load(["config"]).then(function() {
    var pattern, patterns;
    if (mod.src == null) {
      mod.src = "src";
    }
    if (mod.spec == null) {
      mod.spec = "spec";
    }
    if (mod.dest) {
      if (options.refresh) {
        rimraf.sync(mod.dest);
      }
      fs.writeDir(mod.dest);
    }
    if (mod.specDest) {
      if (options.refresh) {
        rimraf.sync(mod.specDest);
      }
      fs.writeDir(mod.specDest);
    }
    patterns = [];
    if (fs.isDir(mod.src)) {
      pattern = path.join(mod.src, "**", "*.js");
      patterns.push(pattern);
    }
    if (fs.isDir(mod.spec)) {
      pattern = path.join(mod.spec, "**", "*.js");
      patterns.push(pattern);
    }
    return patterns;
  });
};
