// Generated by CoffeeScript 1.12.4
var createListeners, emptyFunction, fs, initModule, path, rimraf, transformFiles;

emptyFunction = require("emptyFunction");

rimraf = require("rimraf");

path = require("path");

fs = require("fsx");

transformFiles = require("./transformFiles");

initModule = require("./initModule");

module.exports = function(mod) {
  return initModule(mod).then(function(include) {
    var exclude, listeners;
    exclude = path.join("**", "{node_modules,__tests__,__mocks__}", "**");
    listeners = createListeners(mod.config.babel || {});
    return mod.watch({
      include: include,
      exclude: exclude
    }, listeners);
  });
};

createListeners = function(config) {
  return {
    ready: emptyFunction,
    add: function(file) {
      var green;
      green = log.color.green;
      log.moat(1);
      log.white("File added:\n  " + (green(file.path)));
      log.moat(1);
      return transformFiles([file]);
    },
    change: function(file) {
      return transformFiles([file]);
    },
    unlink: function(file) {
      if (file.dest && fs.exists(file.dest)) {
        rimraf.sync(file.dest);
      }
      if (file.mapDest && fs.exists(file.mapDest)) {
        return rimraf.sync(file.mapDest);
      }
    }
  };
};
